"""The rewrite of portable SQL into PostgreSQL: pure text, so it runs everywhere."""

from __future__ import annotations

import pytest

from observe.storage import StorageError
from observe.storage.pg_dialect import table_info_query, translate_sql
from observe.storage.schema import MIGRATIONS


def test_placeholders_become_driver_placeholders_and_percent_is_doubled():
    assert translate_sql("SELECT a FROM t WHERE b=? AND c LIKE '50%' AND d=?") == \
        "SELECT a FROM t WHERE b=%s AND c LIKE '50%%' AND d=%s"


def test_without_arguments_the_statement_is_left_alone():
    assert translate_sql("SELECT key FROM s WHERE key LIKE 'retention.%'", has_args=False) == \
        "SELECT key FROM s WHERE key LIKE 'retention.%'"


def test_a_question_mark_inside_a_string_is_not_a_placeholder():
    assert translate_sql("SELECT '?' , ?") == "SELECT '?' , %s"


def test_insert_or_ignore_becomes_on_conflict_do_nothing():
    assert translate_sql("INSERT OR IGNORE INTO t (a) VALUES (?)") == \
        "INSERT INTO t (a) VALUES (%s) ON CONFLICT DO NOTHING"
    assert translate_sql("INSERT OR IGNORE INTO t (a) VALUES (?) RETURNING a") == \
        "INSERT INTO t (a) VALUES (%s) ON CONFLICT DO NOTHING RETURNING a"


def test_insert_or_replace_is_refused():
    with pytest.raises(StorageError):
        translate_sql("INSERT OR REPLACE INTO t (a) VALUES (?)")


def test_column_types_follow_postgresql_widths():
    out = translate_sql("CREATE TABLE IF NOT EXISTS t (id INTEGER PRIMARY KEY AUTOINCREMENT, "
                        "ts REAL NOT NULL, n INTEGER DEFAULT 0, b BLOB, note TEXT DEFAULT 'REAL')")
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out
    assert "ts DOUBLE PRECISION NOT NULL" in out
    assert "n BIGINT DEFAULT 0" in out and "b BYTEA" in out
    assert "DEFAULT 'REAL'" in out  # a string literal is never rewritten


def test_a_plain_integer_primary_key_still_assigns_itself():
    assert "GENERATED BY DEFAULT AS IDENTITY" in translate_sql(
        "CREATE TABLE t (id INTEGER PRIMARY KEY)")


def test_without_rowid_is_dropped():
    assert "WITHOUT" not in translate_sql("CREATE TABLE t (a INTEGER) WITHOUT ROWID")


def test_dml_keeps_its_words():
    assert translate_sql("SELECT CAST(a AS INTEGER) FROM t") == "SELECT CAST(a AS INTEGER) FROM t"


def test_two_argument_max_and_min_are_greatest_and_least_but_aggregates_stay():
    assert translate_sql("UPDATE t SET a=MAX(a, excluded.a), b=min(b, ?), c=(SELECT MAX(x) FROM u)"
                         ) == ("UPDATE t SET a=GREATEST(a, excluded.a), b=LEAST(b, %s), "
                               "c=(SELECT MAX(x) FROM u)")


def test_a_comma_inside_a_nested_call_does_not_make_an_aggregate_scalar():
    assert translate_sql("SELECT MAX(COALESCE(a, 0)) FROM t") == \
        "SELECT MAX(COALESCE(a, 0)) FROM t"


def test_create_view_if_not_exists_is_create_or_replace():
    assert translate_sql("CREATE VIEW IF NOT EXISTS v AS SELECT 1") == \
        "CREATE OR REPLACE VIEW v AS SELECT 1"


def test_pragma_table_info_is_a_catalogue_query():
    sql, args = table_info_query("PRAGMA table_info(ingest_keys)")
    assert "information_schema.columns" in sql and args == ("ingest_keys",)
    assert table_info_query("SELECT 1") is None


def test_every_core_schema_step_translates_without_leaving_sqlite_forms():
    for version, steps in MIGRATIONS.items():
        for step in steps:
            if callable(step):
                continue
            out = translate_sql(step, has_args=False)
            for token in ("AUTOINCREMENT", "INSERT OR", "WITHOUT ROWID", " REAL", " BLOB"):
                assert token not in out.upper().replace("DOUBLE PRECISION", ""), (version, out)


def test_rowid_becomes_ctid_in_queries_but_not_in_ddl():
    assert translate_sql("SELECT a FROM t ORDER BY ts DESC, rowid DESC") == (
        "SELECT a FROM t ORDER BY ts DESC, ctid DESC")
    assert "ctid" not in translate_sql("CREATE TABLE t (a INTEGER) WITHOUT ROWID")
