"""Turn the portable SQL that units of work carry into PostgreSQL.

Units and schema steps are written once, in the SQL both backends share: `?` placeholders,
`INSERT OR IGNORE`, `INTEGER PRIMARY KEY AUTOINCREMENT`, `REAL`, the two-argument `MAX` and `MIN`
and `PRAGMA table_info`. The PostgreSQL backend rewrites those forms here, so no caller ever
learns which backend is in use (docs/DATA-API-DESIGN.md section 12). This module is pure text
handling and imports no driver.
"""

from __future__ import annotations

import re

from .base import StorageError

_DDL_START = re.compile(r"^\s*(?:CREATE|ALTER)\b", re.IGNORECASE)
_INSERT_OR_IGNORE = re.compile(r"^(\s*INSERT)\s+OR\s+IGNORE\b", re.IGNORECASE)
_INSERT_OR_OTHER = re.compile(r"^\s*INSERT\s+OR\s+(?:REPLACE|ROLLBACK|ABORT|FAIL)\b", re.IGNORECASE)
_AUTOINC = re.compile(r"\bINTEGER\s+PRIMARY\s+KEY(?:\s+AUTOINCREMENT)?\b", re.IGNORECASE)
_CREATE_VIEW_IF_ABSENT = re.compile(r"^(\s*CREATE)\s+VIEW\s+IF\s+NOT\s+EXISTS\b", re.IGNORECASE)
_RETURNING =re.compile(r"\sRETURNING\s", re.IGNORECASE)
_TYPE_WORDS = (
    (re.compile(r"\bINTEGER\b", re.IGNORECASE), "BIGINT"),
    (re.compile(r"\bREAL\b", re.IGNORECASE), "DOUBLE PRECISION"),
    (re.compile(r"\bBLOB\b", re.IGNORECASE), "BYTEA"),
    (re.compile(r"\s+WITHOUT\s+ROWID\b", re.IGNORECASE), ""),
)
_PRAGMA_TABLE_INFO = re.compile(r"^\s*PRAGMA\s+table_info\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)\s*;?\s*$",
                                re.IGNORECASE)
_ROWID = re.compile(r"\browid\b", re.IGNORECASE)
_SCALAR_FUNCS = re.compile(r"\b(MAX|MIN)\s*\(", re.IGNORECASE)


def _split_quoted(sql: str) -> list[tuple[bool, str]]:
    """Split into (is_literal, text) parts so rewrites never touch a quoted string or name."""
    parts: list[tuple[bool, str]] = []
    i, start, n = 0, 0, len(sql)
    while i < n:
        ch = sql[i]
        if ch in ("'", '"'):
            if i > start:
                parts.append((False, sql[start:i]))
            j = i + 1
            while j < n:
                if sql[j] == ch:
                    if j + 1 < n and sql[j + 1] == ch:
                        j += 2
                        continue
                    break
                j += 1
            parts.append((True, sql[i:j + 1]))
            i = start = j + 1
        else:
            i += 1
    if start < n:
        parts.append((False, sql[start:]))
    return parts


def _scalar_minmax(code: str) -> str:
    """MAX(a, b) and MIN(a, b) with a top-level comma are the scalar forms: GREATEST and LEAST."""
    out, pos = [], 0
    for m in _SCALAR_FUNCS.finditer(code):
        if m.start() < pos:
            continue
        depth, j, comma = 1, m.end(), False
        while j < len(code) and depth:
            c = code[j]
            depth += (c == "(") - (c == ")")
            comma = comma or (c == "," and depth == 1)
            j += 1
        if comma:
            out.append(code[pos:m.start()])
            out.append("GREATEST(" if m.group(1).upper() == "MAX" else "LEAST(")
            pos = m.end()
    out.append(code[pos:])
    return "".join(out)


def translate_sql(sql: str, *, has_args: bool = True) -> str:
    """The PostgreSQL form of one portable statement. Placeholders become `%s`; with arguments
    a literal percent sign is doubled, as the driver requires."""
    if _INSERT_OR_OTHER.match(sql):
        raise StorageError("INSERT OR REPLACE and its relatives are not portable; "
                           "write INSERT ... ON CONFLICT DO UPDATE")
    ddl = bool(_DDL_START.match(sql))
    ignore = bool(_INSERT_OR_IGNORE.match(sql))
    if ignore:
        sql = _INSERT_OR_IGNORE.sub(r"\1", sql, count=1)
    if ddl:
        sql = _CREATE_VIEW_IF_ABSENT.sub(r"\1 OR REPLACE VIEW", sql, count=1)
        sql = _AUTOINC.sub("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
    out = []
    for literal, text in _split_quoted(sql):
        if literal:
            out.append(text.replace("%", "%%") if has_args else text)
            continue
        if ddl:
            for pattern, repl in _TYPE_WORDS:
                text = pattern.sub(repl, text)
        text = _scalar_minmax(text)
        if not ddl:
            text = _ROWID.sub("ctid", text)  # insertion-order tie break; PostgreSQL has no rowid
        if has_args:
            text = text.replace("%", "%%").replace("?", "%s")
        out.append(text)
    result = "".join(out)
    if ignore:
        result = result.rstrip().rstrip(";")
        m = _RETURNING.search(result)
        result = (result[:m.start()] + " ON CONFLICT DO NOTHING" + result[m.start():] if m
                  else result + " ON CONFLICT DO NOTHING")
    return result


def table_info_query(sql: str) -> tuple[str, tuple[str]] | None:
    """`PRAGMA table_info(t)` as a catalogue query that returns (cid, name) rows, or None when
    the statement is something else."""
    m = _PRAGMA_TABLE_INFO.match(sql)
    if not m:
        return None
    return ("SELECT ordinal_position - 1, column_name FROM information_schema.columns "
            "WHERE table_schema = current_schema() AND table_name = %s "
            "ORDER BY ordinal_position", (m.group(1).lower(),))
